name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  extension-ci:
    uses: irodori-table/irodori-kit/.github/workflows/extension-ci.yml@v0.6.9
    with:
      manifest-root: "."
      package-command: "make package"
      duckdb-backed: false
